# Generated by Django 5.2.6 on 2025-09-26 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_no', models.CharField(blank=True, max_length=17, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Physical address')),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='user_pic', to='wagtailimages.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
