# Generated by Django 5.2.6 on 2025-12-16 10:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=wagtail.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
