# Generated by Django 5.2.6 on 2025-09-26 10:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_box_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_bottom_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_bottom_image_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_top_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_top_image_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 0), ('subtitle', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroFlatButtonHref',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroFlatButtonTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroOutlineButtonHref',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroOutlineButtonTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroSubtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_items',
            field=wagtail.fields.StreamField([('portfolio_item', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('name', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Google Play Store URL', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Apple App Store URL', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'max_value': 2100, 'min_value': 2000, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('client', 0), ('client_logo', 1), ('image', 1), ('platform', 0), ('description', 2), ('technologies', 5), ('website_url', 6), ('play_store_url', 7), ('app_store_url', 8), ('year', 9)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 0), ('subtitle', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_media_items',
            field=wagtail.fields.StreamField([('social_media', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('link', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle_box',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle_signup',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
