# Generated by Django 5.2.6 on 2026-04-28 07:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_portfolio_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='portfolio_items',
            field=wagtail.fields.StreamField([('portfolio_item', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('name', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Google Play Store URL', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Download path', 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'max_value': 2100, 'min_value': 2000, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('platform', 0), ('description', 2), ('features', 5), ('website_url', 6), ('play_store_url', 7), ('download_path', 8), ('year', 9)]], {})}, null=True),
        ),
    ]
